### ISSUE TITLE
`prepend_before_filter` is deprecated and should be replaced with `prepend_before_action`

### ISSUE THREAD

**Issue by tosie** [indirect/rails-footnotes#141]
Rails 4.2 deprecated `prepend_before_filter` (used in lib/rails-footnotes/extension.rb). `prepend_before_action` should be used instead.

See https://github.com/rails/rails/blob/v4.2.5/guides/source/4_2_release_notes.md#notable-changes-1.

**Comment by tosie** [comment]
Sorry for this addition, but `after_filter` has been deprecated as well.

It is used in

* lib/rails-footnotes/extension.rb
* lib/rails-footnotes/abstract_note.rb

and should be replaced with `after_action`.

**Comment by Intrepidd** [comment]
We started doing that then reverted the changes in #135 because the new methods did not exist in Rails 3.2.

I guess we'll have to decide between doing a check of the rails version to call the correct method or start dropping support for 3.2.

**Comment by tosie** [comment]
Understandable. My guess is, that this gem is used in old and new rails versions. A version check seems to be the (moral) right thing to do. On the other hand it is always easier to follow new versions and don't bother with older ones.

Your decision :smile:

**Comment by Intrepidd** [comment]
Yep it's a tough one but rails 3.2 is only supported for severe security patches.

Anyway thanks for the issue, I'll close it whenever I come up with a conclusion and commit the changes.

**Comment by tosie** [comment]
No problem. Thanks for the replies :wink:
