### ISSUE TITLE
Issue with the href="#" attributes in the rails-footnotes links

### ISSUE THREAD

**Issue by AntonTrapp** [indirect/rails-footnotes#143]
Whenever you use a framework like AngularJS, Ember, ... or write your own JS that has a frontend router which is handling the URL in JavaScript you get your pages and applications totally messed up due to the href="#" links which always lead you to your home screen (due to the URL change).

Since HTML 5 a-tags without a href attribute are safe (placeholder hyperlinks) - maybe they can be removed? If not, this should be clearly be noted in the documentation, because it affects most modern JS frameworks on the client (and a lot of hand made stuff too). I don't think anybody really needs the href (javascript disabled together with rails-footnotes???) , or am I wrong here?

**Comment by indirect** [comment]
Sadly this project is not designed to support SPAs, although I would be open to contributions to add support.
