### ISSUE TITLE
Hook destructively changes global config

### ISSUE THREAD

**Issue by ypresto** [indirect/rails-footnotes#158]
From sample code in README.rb

```rb
config.before {|controller, filter| filter.notes = controller.class.name =~ /Message/ && \
    controller.action_name == 'index' ? [:assigns] : []}
```

This will destructively changes `filter.notes` for later calls.

Passed block parameter filter is class instance of Footnotes::Filter, which is global singleton.
https://github.com/josevalim/rails-footnotes/blob/0ca9f4c4ce404113994f81552c304d8fd326ac1c/lib/rails-footnotes/filter.rb#L33

Also, it maybe not thread safe.

**Comment by indirect** [comment]
The class attributes should be per-thread now, try 7.0 or higher.
