### ISSUE TITLE
[FYI] Alternative for this gem

### ISSUE THREAD

**Issue by ypresto** [indirect/rails-footnotes#159]
This gem looks obsolete, unfortunately.
If you want to see only performance / query info, rack-mini-profiler is good alternative..!
https://github.com/MiniProfiler/rack-mini-profiler

Anyway thanks to author of this gem, it saved my time for long time..!

**Comment by Intrepidd** [comment]
Hi,
Indeed rack-mini-profiler is a very good alternative to this gem.

If anyone is interested in helping to make this gem compatible to the latest rails versions, feel free to help ! I started a `spring-cleaning` branch but unfortunately have no time to work on it at the moment.

**Comment by indirect** [comment]
My fork works with Rails 6: https://github.com/indirect/rails-footnotes.

You can install it directly by adding `gem "rails6-footnotes", "~> 5.0"` to your Gemfile.

**Comment by Intrepidd** [comment]
Hi @indirect 

Thanks a lot for this! 

If this works with rails 6 I say we merge it here.
Could you open a PR? 

Since you made the effort of creating a new gem, would you be interested in taking over?

**Comment by indirect** [comment]
@Intrepidd sure, I guess I might as well take over if I've gone this far 😅 I'd be great to merge it in and release a new version of the official gem! I'll open a PR.

**Comment by Intrepidd** [comment]
Fabulous! I'll give you access to the repository as well, thanks for chiming in to resurrect this great project! 

We can release a major version right after, and then we can work out rubygems access if you want it

**Comment by indirect** [comment]
I've released `rails-footnotes 5.0.0`, which supports Ruby 3+ and Rails 6+.
