### ISSUE TITLE
Incompatibility with ActiveStorage

### ISSUE THREAD

**Issue by apekshit-tewathia** [indirect/rails-footnotes#161]
Rails Version: 5.2.1
Ruby Version: 2.3.7
Server stops responding on loading multiple images on any view page

`
<% @meal.images.each do |image| %>
  <%= image_tag image %>
<% end %>
`

On debugging, found the following error:
> Footnotes Footnotes::Notes::ViewNote Exception: undefined method `[]' for nil:NilClass

Had to remove the gem eventually

**Comment by indirect** [comment]
I fixed this in my fork, which you can use with `gem "rails6-footnotes", "~> 5.0"`.

**Comment by indirect** [comment]
I've released v5 of rails-footnotes, which fixes this problem.
