### ISSUE TITLE
Request for Changelog Entries Regarding Minimum/Supported Ruby Versions

### ISSUE THREAD

**Issue by brandondrew** [indirect/rails-footnotes#172]
The [CHANGELOG](https://github.com/indirect/rails-footnotes/blob/main/CHANGELOG) mentions version 4 dropping support for Ruby 1.8.  It would be helpful to have this information for other changes in supported Ruby versions, to allow us to more easily find a usable version prior to upgrading to Ruby 3.x.

It would also be helpful to include a mention of [the current requirement](https://github.com/indirect/rails-footnotes/blob/main/rails-footnotes.gemspec) in the [README](https://github.com/indirect/rails-footnotes).
 
Thanks!

**Comment by indirect** [comment]
I have only personally released versions 5.0.0 and up, and only used those versions with Ruby 3.0 and up. It worked for me, but it may not work for you. I have no information about versions before 5 beyond "they didn't work for me on Ruby 3".

No Ruby version (or anything else, for that matter) is officially supported—you get what's in the repo, and pull requests are welcome if you need to make changes for it to work for you.
