### ISSUE TITLE
Issue with bundle install on Rails 7

### ISSUE THREAD

**Issue by amukater** [indirect/rails-footnotes#195]
```
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Could not find compatible versions

Because rails-footnotes >= 5.0.0 depends on rails ~> 6.0
  and Gemfile depends on rails = 7.0.6,
  rails-footnotes >= 5.0.0 cannot be used.
So, because Gemfile depends on rails-footnotes ~> 5.0,
  version solving has failed.
```

Hello maintainers,

Firstly, I'd like to express my gratitude for the effort put into supporting Rails 7. It's highly appreciated!

I've encountered an issue when trying to run bundle install with Rails 7. Upon inspecting the [Rails Footnotes gem on rubygems.org](https://rubygems.org/gems/rails-footnotes/versions/5.0.0), it appears that it might only be compatible with Rails 6.

Could you please provide some guidance or let me know if there's anything specific I should do to resolve this? Thank you in advance!

**Comment by indirect** [comment]
You need to use the gem from git for now, the version that supports Rails 7 has not yet been released. Try this:

```
# Gemfile
gem "rails-footnotes", github: "indirect/rails-footnotes"
```
