### ISSUE TITLE
Why is unknown traces of table creation seen in the logs

### ISSUE THREAD

**Issue by rajeshkp** [indirect/rails-footnotes#94]
Why is unknown traces of table creation seen in the logs, how do I prevent this.

UNKNOWN (trace)
SHOW CREATE TABLE foo
SCHEMA (0.002ms)  
UNKNOWN (trace)
SHOW FULL FIELDS FROM foo
SCHEMA (0.003ms)

**Comment by indirect** [comment]
Happy to reopen and investigate if you can provide reproduction steps, but closing for now since I am not able to reproduce this.
